# Build
FROM jetbrains/teamcity-minimal-agent:2021.1.4-linux

USER root

WORKDIR /apps

# Install system dependencies
RUN apt update && \
    apt install -y \
      sudo \
      wget \
      curl \
      ca-certificates \
      apt-transport-https \
      rsync \
      libc6 \
      libgcc1 \
      libgssapi-krb5-2 \
      libicu66 \
      libssl1.1 \
      libstdc++6 \
      zlib1g \
      libgdiplus \
      gnupg \
      software-properties-common && \
    rm -rf /var/lib/apt/lists/*

# Install NodeJS 14 (+ Angular CLI)
ENV NODE_VERSION=14.18.1
ENV NVM_DIR=/usr/local/nvm
ENV NODE_PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin
RUN mkdir -p $NVM_DIR && \
    wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash && \
    . $NVM_DIR/nvm.sh && \
    nvm install $NODE_VERSION && \
    nvm alias default $NODE_VERSION && \
    nvm use default && \
    ln -s $NODE_PATH/node /usr/bin/node && \
    ln -s $NODE_PATH/npm /usr/bin/npm && \
    ln -s $NODE_PATH/npx /usr/bin/npx
## Angluar CLI
RUN npm install --global --allow-root --unsafe-perm=true @angular/cli

# Install Dotnet 5 SDK
RUN wget "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb" -O packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    rm packages-microsoft-prod.deb && \
    apt update && \
    apt install -y dotnet-sdk-5.0 && \
    rm -rf /var/lib/apt/lists/*

# Install Wine (+ InnoSetup)
RUN dpkg --add-architecture i386 && \
    apt update && \
    wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add - && \
    apt-add-repository "deb http://dl.winehq.org/wine-builds/ubuntu/ $(lsb_release -cs) main" && \
    apt install -y --install-recommends winehq-stable && \
    rm -rf /var/lib/apt/lists/*

  # apt install -y wine64 wine32 xvfb && \
  #   add-apt-repository -y ppa:ubuntu-wine && \
  #   apt update && \
  #   apt install -y wine && \
  #   winetricks allfonts && \
## InnoSetup
# RUN wget "https://files.jrsoftware.org/is/6/innosetup-6.2.0.exe" -O innosetup.exe && \
#     wine innosetup.exe /SP- /VERYSILENT /ALLUSERS /SUPPRESSMSGBOXES /DOWNLOADISCRYPT=1 && \
#     rm innosetup.exe

# Start the agent
CMD ["/run-services.sh"]