version: "3"
services:

  server:
    image: jetbrains/teamcity-server:2021.1.4-linux
    container_name: teamcity-server
    hostname: teamcity-server
    ports:
      - 8111:8111
    volumes:
      - /apps/teamcity/data:/data/teamcity_server/datadir
      - /apps/teamcity/logs:/opt/teamcity/logs
    user: root
    restart: unless-stopped

  agent:
    build:
      dockerfile: ./dockerfile-agent
    container_name: teamcity-agent
    hostname: teamcity-agent
    volumes:
      - /apps/teamcity/agent:/data/teamcity_agent/conf
    environment:
      - SERVER_URL=teamcity-server
    user: root
    restart: unless-stopped